MotorDepot.WEB/Models/VehicleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MotorDepot.WEB.Models
{
    public class CreateVehicleViewModel
    {
        [Required]
        [Display(Name="Название")]
        public String Name { get; set; }

        [Required]
        [Display(Name="Тип")]
        public Int32 VehicleClassId { get; set; }

        [Required]
        [Display(Name="Кол-во сидений")]
        public Int32 SeatsNumber { get; set; }

        [Required]
        public DimensionsViewModel Dimensions { get; set; }

        [Required]
        public CreateDriveViewModel Drive { get; set; }

        [Required]
        [Display(Name="Фото")]
        public HttpPostedFileBase Photo { get; set; }
    }

    public class EditVehicleViewModel
    {
        public Int32 Id { get; set; }

        [Required]
        [Display(Name = "Название")]
        public String Name { get; set; }

        [Required]
        [Display(Name = "Тип")]
        public Int32 VehicleClassId { get; set; }

        [Required]
        [Display(Name = "Кол-во сидений")]
        public Int32 SeatsNumber { get; set; }

        [Required]
        public DimensionsViewModel Dimensions { get; set; }
        [Required]
        public CreateDriveViewModel Drive { get; set; }

        [Display(Name = "Фото")]
        public HttpPostedFileBase Photo { get; set; }
    }

    public class VehicleViewModel
    {
        public Int32 Id { get; set; }


        [Required]
        [Display(Name = "Название")]
        public String Name { get; set; }

        [Required]
        [Display(Name = "Тип")]
        public VehicleClassViewModel Class { get; set; }

        [Required]
        [Display(Name = "Кол-во сидений")]
        public Int32 SeatsNumber { get; set; }

        [Required]
        public DimensionsViewModel Dimensions { get; set; }

        [Required]
        public DriveViewModel Drive { get; set; }

        [Required]
        [Display(Name = "Фото")]
        public ImageViewModel Photo { get; set; }
    }

    public class DimensionsViewModel
    {
        [Required]
        [Display(Name = "Длина(м)")]
        public Double Length { get; set; }

        [Required]
        [Display(Name="Ширина(м)")]
        public Double Width { get; set; }

        [Required]
        [Display(Name="Высота(м)")]
        public Double Height { get; set; }
    }

    public class CreateDriveViewModel
    {

        public Int32 Id { get; set; }

        [Required]
        [Display(Name="Название")]
        public String Name { get; set; }

        [Required]
        [Display(Name="Объем(л)")]
        public Double Volume { get; set; }

        [Required]
        [Display(Name="Тип привода")]
        public VehicleDriveType DriveType { get; set; }

        [Required]
        [Display(Name="Топливо")]
        public Int32 FuelTypeId { get; set; }

        [Required]
        [Display(Name="Кол-во цилиндров")]
        public Int32 CylindersNumber { get; set; }

        [Required]
        [Display(Name="Максимальная скорость(км/ч)")]
        public Int32 MaxSpeed { get; set; }

        [Required]
        [Display(Name="Разгон от 0 до 100(с)")]
        public Double AccelerationTime { get; set; }
    }

    public class DriveViewModel
    {
        [Display(Name = "Название")]
        public String Name { get; set; }

        [Display(Name = "Объем")]
        public Double Volume { get; set; }

        [Display(Name = "Тип привода")]
        public VehicleDriveType DriveType { get; set; }

        [Display(Name = "Топливо")]
        public FuelTypeViewModel FuelType { get; set; }

        [Display(Name = "Кол-во цилиндров")]
        public Int32 CylindersNumber { get; set; }

        [Display(Name = "Максимальная скорость")]
        public Int32 MaxSpeed { get; set; }

        [Display(Name = "Разгон от 0 до 100")]
        public Double AccelerationTime { get; set; }
    }


    public class VehicleClassViewModel
    {

        public Int32 Id { get; set; }
        [Display(Name="Тип авто")]
        public String Name { get; set; }
        public String Description { get; set; }
    }

    public class FuelTypeViewModel
    {
        public Int32 Id { get; set; }
        public String Name { get; set; }
    }

    public enum VehicleDriveType
    {
        [Display(Name="Задний привод")]
        RearWheel,

        [Display(Name = "Полный привод")]
        FourWheel,

        [Display(Name = "Передний привод")]
        FrontWheel
    }



}

MotorDepot.WEB/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using MotorDepot.WEB.Abstract;
using MotorDepot.WEB.Extensions;
using MotorDepot.WEB.Models;

namespace MotorDepot.WEB.Controllers
{
    [Authorize(Roles = "Admin")]
    public class VehicleController : Controller
    {
        private IControllersLogics _sLogics;
        private IVehiclesLogics _logics;

        public VehicleController(IControllersLogics sLogics, IVehiclesLogics logics)
        {
            _sLogics = sLogics;
            _logics = logics;
        }

        public ActionResult Index()
        {
            return View(_logics.GetVehicles());
        }

        public ActionResult Create()
        {
            ViewBag.FuelTypes = _logics.GetFuelTypesSelectList();
            ViewBag.VehicleClasses = _sLogics.GetVehicleClassesSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(CreateVehicleViewModel model)
        {


            if (ModelState.IsValid)
            {
                _logics.Create(model);
                SuccessMessage("Автомобиль успешно добавлен");
                return RedirectToAction("Index");
            }

            ViewBag.FuelTypes = _logics.GetFuelTypesSelectList();
            ViewBag.VehicleClasses = _sLogics.GetVehicleClassesSelectList();
            ErrorMessage("При добавлении автомобиля произошла ошибка");
            return View(model);

        }

        public ActionResult Edit(Int32 id)
        {
            var model = _logics.GetEditVehicleInfo(id);

            var vehicleClasses = _sLogics.GetVehicleClassesSelectList();
            vehicleClasses.FirstOrDefault(x => Int32.Parse(x.Value) == model.VehicleClassId).Selected = true;

            var fuelTypes = _logics.GetFuelTypesSelectList();
            fuelTypes.FirstOrDefault(x => Int32.Parse(x.Value) == model.Drive.FuelTypeId).Selected = true;

            ViewBag.VehicleClasses = vehicleClasses;
            ViewBag.FuelTypes = fuelTypes;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditVehicleViewModel model)
        {
            if (ModelState.IsValid)
            {
                _logics.SubmitEdit(model);
                SuccessMessage("Автомобиль успешно изменен");
                return RedirectToAction("Index");
            }
            ErrorMessage("При изменении автомобиля произошла ошибка");
            return View(model);
        }



        [Authorize]
        public ActionResult FullInfo(Int32 id)
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_fullVehicleInfo", _logics.GetVehicleInfo(id));
            }
            return PartialView("_fullVehicleInfo", _logics.GetVehicleInfo(id));
        }

        public ActionResult FreeVehicles(DateTime startTime, DateTime endTime)
        {
            return PartialView("_chooseAuto", _logics.GetFreeVehicles(startTime, endTime));
        }


        public ActionResult Delete(Int32 id)
        {
            if (_logics.DeleteVehicle(id))
            {

                SuccessMessage("Автомобиль успешно удален", "Отменить",
                    "/Vehicle/UndoDeletion/" + id);
                return RedirectToAction("Index");
            }

            ErrorMessage(
                "Невозможно удалить данный автомобиль. Возможно он участвует в выполняемых рейсах");
            return RedirectToAction("Index");

        }

        
        public ActionResult UndoDeletion(Int32 id)
        {
            _logics.UndoDeletion(id);

            return RedirectToAction("Index");
        }


        #region privateMethods
        private Int32 CurrentUserId
        {
            get
            {
                var authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
                if (authCookie != null)
                {
                    var ticket = FormsAuthentication.Decrypt(authCookie.Value);
                    var id = Convert.ToInt32(ticket.UserData);
                    return id;
                }
                return 0;
            }
        }

        private void TempMessage(TempMessageType type, String message, String linkText = null, String linkHref = null)
        {
            TempMessage tempMessage;
            if (linkText != null && linkHref != null)
                tempMessage = new LinkTempMessage(type, message, linkText, linkHref);
            else tempMessage = new TempMessage(type, message);

            if (TempData.ContainsKey("TempMessages"))
                ((Collection<TempMessage>)(TempData["TempMessages"])).Add(tempMessage);
            else TempData.Add("TempMessages", new Collection<TempMessage> { tempMessage });
        }

        private void SuccessMessage(String message, String linkText = null, String linkHref = null)
        {
            TempMessage(TempMessageType.Success, message, linkText, linkHref);
        }

        private void ErrorMessage(String message, String linkText = null, String linkHref = null)
        {
            TempMessage(TempMessageType.Error, message, linkText, linkHref);
        }

        #endregion

    }
}

MotorDepot.WEB/Views/Vehicle/Create.cshtml
@model MotorDepot.WEB.Models.CreateVehicleViewModel
@{
    ViewBag.Title = "AddVehicle";
}

@using (Html.BeginForm("Create", "Vehicle", FormMethod.Post, new {@class = "ms-form", enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <fieldset class="paper-block">
        <h1>Добавить автомобиль</h1>
        <h2 class="fs-title">Основные данные</h2>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.VehicleClassId)
            @Html.DropDownListFor(x => x.VehicleClassId, (IEnumerable<SelectListItem>)ViewBag.VehicleClasses)
            @Html.ValidationMessageFor(x => x.VehicleClassId)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.SeatsNumber)
            @Html.EditorFor(x => x.SeatsNumber)
            @Html.ValidationMessageFor(x => x.SeatsNumber)
        </div>
        
        <h3 class="fs-subtitle">Габариты</h3>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Height)
            @Html.EditorFor(x => x.Dimensions.Height)
            @Html.ValidationMessageFor(x => x.Dimensions.Height)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Length)
            @Html.EditorFor(x => x.Dimensions.Length)
            @Html.ValidationMessageFor(x => x.Dimensions.Length)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Width)
            @Html.EditorFor(x => x.Dimensions.Width)
            @Html.ValidationMessageFor(x => x.Dimensions.Width)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Photo)
            @Html.EditorFor(x => x.Photo)
            @Html.ValidationMessageFor(x => x.Photo)
        </div>

        <div class="form-buttons">
            <button type="button" class="action-button next">Далее</button>
        </div>
    </fieldset>
    <fieldset class="paper-block">
        <h1>Добавить автомобиль</h1>
        <h2 class="fs-title">Данные двигателя</h2>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.Name)
            @Html.EditorFor(x => x.Drive.Name)
            @Html.ValidationMessageFor(x => x.Drive.Name)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.DriveType)
            @Html.EditorFor(x => x.Drive.DriveType)
            @Html.ValidationMessageFor(x => x.Drive.DriveType)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.FuelTypeId)
            @Html.DropDownListFor(x => x.Drive.FuelTypeId, (IEnumerable<SelectListItem>)ViewBag.FuelTypes)
            @Html.ValidationMessageFor(x => x.Drive.FuelTypeId)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.Volume)
            @Html.EditorFor(x => x.Drive.Volume)
            @Html.ValidationMessageFor(x => x.Drive.Volume)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.CylindersNumber)
            @Html.EditorFor(x => x.Drive.CylindersNumber)
            @Html.ValidationMessageFor(x => x.Drive.CylindersNumber)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.MaxSpeed)
            @Html.EditorFor(x => x.Drive.MaxSpeed)
            @Html.ValidationMessageFor(x => x.Drive.MaxSpeed)
        </div>
        
        <div class="form-group">
            @Html.LabelFor(x => x.Drive.AccelerationTime)
            @Html.EditorFor(x => x.Drive.AccelerationTime)
            @Html.ValidationMessageFor(x => x.Drive.AccelerationTime)
        </div>
        
        <div class="form-buttons">
            <button type="button" class="action-button previous">Назад</button>
            <input type="submit" value="Отправить" class="action-button submit" />
        </div>
    </fieldset>
}

@section scripts {
    @Scripts.Render("~/Scripts/formScripts")
}

MotorDepot.WEB/Views/Vehicle/Edit.cshtml
@model MotorDepot.WEB.Models.EditVehicleViewModel
@{
    ViewBag.Title = "Edit a vehicle";
}

@using (Html.BeginForm("Edit", "Vehicle", FormMethod.Post, new { @class = "ms-form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.Drive.Id)
    
    <fieldset class="paper-block">
        <h1>Редактирования автомобиля</h1>
        <h2 class="fs-title">Основные данные</h2>

        <div class="form-group">
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.VehicleClassId)
            @Html.DropDownListFor(x => x.VehicleClassId, (IEnumerable<SelectListItem>)ViewBag.VehicleClasses)
            @Html.ValidationMessageFor(x => x.VehicleClassId)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.SeatsNumber)
            @Html.EditorFor(x => x.SeatsNumber)
            @Html.ValidationMessageFor(x => x.SeatsNumber)
        </div>

        <h3 class="fs-subtitle">Габариты</h3>

        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Height)
            @Html.EditorFor(x => x.Dimensions.Height)
            @Html.ValidationMessageFor(x => x.Dimensions.Height)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Length)
            @Html.EditorFor(x => x.Dimensions.Length)
            @Html.ValidationMessageFor(x => x.Dimensions.Length)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Dimensions.Width)
            @Html.EditorFor(x => x.Dimensions.Width)
            @Html.ValidationMessageFor(x => x.Dimensions.Width)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Photo)
            @Html.EditorFor(x => x.Photo)
            @Html.ValidationMessageFor(x => x.Photo)
        </div>

        <div class="form-buttons">
            <button type="button" class="action-button next">Далее</button>
        </div>
    </fieldset>
    <fieldset class="paper-block">
        <h1>Редактирование автомобиля</h1>
        <h2 class="fs-title">Данные двигателя</h2>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.Name)
            @Html.EditorFor(x => x.Drive.Name)
            @Html.ValidationMessageFor(x => x.Drive.Name)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.DriveType)
            @Html.EditorFor(x => x.Drive.DriveType)
            @Html.ValidationMessageFor(x => x.Drive.DriveType)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.FuelTypeId)
            @Html.DropDownListFor(x => x.Drive.FuelTypeId, (IEnumerable<SelectListItem>)ViewBag.FuelTypes)
            @Html.ValidationMessageFor(x => x.Drive.FuelTypeId)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.Volume)
            @Html.EditorFor(x => x.Drive.Volume)
            @Html.ValidationMessageFor(x => x.Drive.Volume)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.CylindersNumber)
            @Html.EditorFor(x => x.Drive.CylindersNumber)
            @Html.ValidationMessageFor(x => x.Drive.CylindersNumber)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.MaxSpeed)
            @Html.EditorFor(x => x.Drive.MaxSpeed)
            @Html.ValidationMessageFor(x => x.Drive.MaxSpeed)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Drive.AccelerationTime)
            @Html.EditorFor(x => x.Drive.AccelerationTime)
            @Html.ValidationMessageFor(x => x.Drive.AccelerationTime)
        </div>

        <div class="form-buttons">
            <button type="button" class="action-button previous">Назад</button>
            <input type="submit" value="Сохранить" class="action-button submit" />
        </div>
    </fieldset>
}

@section scripts {
    @Scripts.Render("~/Scripts/formScripts")
}

MotorDepot.WEB/Views/Vehicle/Index.cshtml
@model IEnumerable<MotorDepot.WEB.Models.VehicleViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="vehicles-list paper-block paper-block-full">
    <h1 class="title">Автомобили</h1>
    @foreach (var vehicleInfo in Model)
    {
        <div class="vehicle-info">
            @Html.Partial("_vehicleInfo", vehicleInfo)
        </div>
    }

</div>

@section scripts{
    @Scripts.Render("~/Scripts/vehicleScripts")
}

MotorDepot.WEB/Views/Vehicle/_vehicleInfo.cshtml
@model MotorDepot.WEB.Models.VehicleViewModel

<img src="data:@Model.Photo.Type;base64, @Convert.ToBase64String(Model.Photo.Bytes)" alt="@Model.Name" />
<div class="info">
    <input type="hidden" class="model_id" value="@Model.Id" />
    <h2>@Model.Name</h2>
    <h3>Категория: @Model.Class.Name (@Model.Class.Description)</h3>
    <div class="vehicle-controll-buttons">
        <button type="button" class="vehicle-controll-button more-info-button"><i class="fa fa-info"></i> Подробнее</button>
        <a class="vehicle-controll-button edit-vehicle-button" href="/Vehicle/Edit/@Model.Id"><i class="fa fa-edit"></i> Редактировать</a>
        <a class="vehicle-controll-button remove-vehicle-button" href="/Vehicle/Delete/@Model.Id"><i class="fa fa-remove"></i> Удалить</a>
    </div>
</div>
<div class="clear"></div>